name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: sudo apt update && sudo apt install -y git gpg python3 python3-gnupg
      - name: run lint script
        run: python3 .github/workflows/check.py
